### ISSUE TITLE
人物关系问答  app.py 调用get_target_array() 为什么参数传递不过去   报错就是下面这种

### ISSUE THREAD

**Issue by gengen-yuhuai** [chizhu/KGQA_HLM#20]
Segmentor: Model not loaded!
Postagger: Model not loaded!
127.0.0.1 - - [08/Mar/2022 15:33:35] "GET /KGQA_answer?name=贾宝玉的父亲 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "D:\20220307\env\lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "D:\20220307\env\lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "D:\20220307\env\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\20220307\env\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\20220307\env\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\20220307\env\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\20220307\project\1.0\KGQA_HLM-master\app.py", line 36, in KGQA_answer
    res =ltp.get_target_array(res)
  File "D:\20220307\project\1.0\KGQA_HLM-master\KGQA\ltp.py", line 41, in get_target_array
    target_array.append(seg_array[1])
IndexError: list index out of range

**Comment by xiehou-design** [comment]
ltp.py里面的模型路径没改好

**Comment by gengen-yuhuai** [comment]
已经改好了  确实是路径的问题

**Comment by linmumu0205** [comment]
你好 请问抽取小说中的人物关系relationship如何实现的呢 有相关代码吗

**Comment by xiehou-design** [comment]
> 

那个relation.txt估计是哪里的公开数据集或者人工标注的吧，一般那个relation可以用实体关系抽取模型来做到，不过要标注数据，如果有公开数据集就比较简单了，直接先命名实体识别在关系抽取就会形成”实体-关系-实体“三元组，也就是那个relation.txt的一行5个值

**Comment by linmumu0205** [comment]
> > 
> 
> 那个relation.txt估计是哪里的公开数据集或者人工标注的吧，一般那个relation可以用实体关系抽取模型来做到，不过要标注数据，如果有公开数据集就比较简单了，直接先命名实体识别在关系抽取就会形成”实体-关系-实体“三元组，也就是那个relation.txt的一行5个值

感谢提供思路

**Comment by lililijx** [comment]
> 已经改好了 确实是路径的问题

您好 请问具体是哪里呢 方便告知一下吗 我改了ltp.py里面的路径 好像还是不行

**Comment by gengen-yuhuai** [comment]
将ltp.py文件放到根目录应该就可以了我记得当时是这样操作的&nbsp; ，你可以试试&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月2日(星期天) 晚上10:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chizhu/KGQA_HLM] 人物关系问答  app.py 调用get_target_array() 为什么参数传递不过去   报错就是下面这种 (Issue #20)





  
已经改好了 确实是路径的问题
  
您好 请问具体是哪里呢 方便告知一下吗 我改了ltp.py里面的路径 好像还是不行

**Comment by lililijx** [comment]
抱歉再次打扰，改了之后还是不太行 可以问问您的ltp是什么版本吗，谢谢

**Comment by gengen-yuhuai** [comment]
你是放到app.py同级目录下吗&nbsp; &nbsp; 版本是v3.4.0



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月2日(星期天) 晚上10:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chizhu/KGQA_HLM] 人物关系问答  app.py 调用get_target_array() 为什么参数传递不过去   报错就是下面这种 (Issue #20)





 
抱歉再次打扰，改了之后还是不太行 可以问问您的ltp是什么版本吗，谢谢

**Comment by lililijx** [comment]
> 

确实放在同级目录下了，但是还是不太行。我的版本也是3.4.0 ，但是pyltp是0.4.0

**Comment by gengen-yuhuai** [comment]
我用的是 0.2.1&nbsp; &nbsp;或许是版本的问题。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月2日(星期天) 晚上10:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chizhu/KGQA_HLM] 人物关系问答  app.py 调用get_target_array() 为什么参数传递不过去   报错就是下面这种 (Issue #20)





   
确实放在同级目录下了，但是还是不太行。我的版本也是3.4.0 ，但是pyltp是0.4.0

**Comment by lililijx** [comment]
> 

那请问您python用的什么版本呢，我用的3.8 所以没找到0.2.1的版本

**Comment by gengen-yuhuai** [comment]
3.6&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月2日(星期天) 晚上10:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chizhu/KGQA_HLM] 人物关系问答  app.py 调用get_target_array() 为什么参数传递不过去   报错就是下面这种 (Issue #20)





   
那请问您python用的什么版本呢，我用的3.8 所以没找到0.2.1的版本

**Comment by lililijx** [comment]
好吧 谢谢您回答我这么多问题 十分感谢 我会换0.2.1试试的！

**Comment by gengen-yuhuai** [comment]
pyltp-0.2.1-cp36-cp36m-win_amd64.whl  我记得当时 pip 安装不了，  可以网上找一下这哥whl包  直接解压到你的环境库里。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月2日(星期天) 晚上10:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chizhu/KGQA_HLM] 人物关系问答  app.py 调用get_target_array() 为什么参数传递不过去   报错就是下面这种 (Issue #20)





   
确实放在同级目录下了，但是还是不太行。我的版本也是3.4.0 ，但是pyltp是0.4.0
