### ISSUE TITLE
请教一下，问答界面会报错，搜索界面也搜不到想要的目标

### ISSUE THREAD

**Issue by J-Jzf** [chizhu/KGQA_HLM#25]
如题，
![image](https://github.com/chizhu/KGQA_HLM/assets/116648963/1a225201-a639-4fa8-b8d8-aa8df4f93129)
127.0.0.1 - - [17/Apr/2024 19:38:17] "GET /KGQA_answer?name=贾宝玉的爸爸是谁 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "D:\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "D:\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
  File "D:\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "d:\Microsoft VS Code\vs work\codeworkvs\py\py\dachuang\KGQA\KGQA_HLM-master\app.py", line 31, in KGQA_answer
    json_data = get_KGQA_answer(get_target_array(str(question)))
  File "d:\Microsoft VS Code\vs work\codeworkvs\py\py\dachuang\KGQA\KGQA_HLM-master\KGQA\ltp.py", line 33, in get_target_array
    seg_array=cut_words(words)
  File "d:\Microsoft VS Code\vs work\codeworkvs\py\py\dachuang\KGQA\KGQA_HLM-master\KGQA\ltp.py", line 8, in cut_words
    segmentor = pyltp.Segmentor()
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. pyltp.Segmentor(model_path: str, lexicon_path: str = None, force_lexicon_path: str = None)

Invoked with:

![image](https://github.com/chizhu/KGQA_HLM/assets/116648963/b133fb20-24af-43c1-824e-7c7d0a0966fe)
![image](https://github.com/chizhu/KGQA_HLM/assets/116648963/b4467c84-76ad-4164-b6d8-84900ab56cc6)

**Comment by fanyingmanliangpai** [comment]
> 如题， ![image](https://private-user-images.githubusercontent.com/116648963/323202557-1a225201-a639-4fa8-b8d8-aa8df4f93129.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNzYzNTcsIm5iZiI6MTcxNTE3NjA1NywicGF0aCI6Ii8xMTY2NDg5NjMvMzIzMjAyNTU3LTFhMjI1MjAxLWE2MzktNGZhOC1iOGQ4LWFhOGRmNGY5MzEyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOFQxMzQ3MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjM3ZTI0MjVkYTkzNDY1NzliYzZlZWRiOGIxZjYxMGFiMDU0MDY0MmZlNmZiNjc0M2Q0ZGZhN2E0NWYzNGIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cn_qJDhipftjaRxEKze3cwpjtu4GTa25lK78tbFCkt0) 127.0.0.1 - - [17/Apr/2024 19:38:17] "GET /KGQA_answer?name=贾宝玉的爸爸是谁 HTTP/1.1" 500 - Traceback (most recent call last): File "D:\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1498, in **call** return self.wsgi_app(environ, start_response) File "D:\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1476, in wsgi_app response = self.handle_exception(e) File "D:\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1473, in wsgi_app response = self.full_dispatch_request() File "D:\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 882, in full_dispatch_request rv = self.handle_user_exception(e) File "D:\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 880, in full_dispatch_request rv = self.dispatch_request() File "D:\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 865, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args) # type: ignore[no-any-return] File "d:\Microsoft VS Code\vs work\codeworkvs\py\py\dachuang\KGQA\KGQA_HLM-master\app.py", line 31, in KGQA_answer json_data = get_KGQA_answer(get_target_array(str(question))) File "d:\Microsoft VS Code\vs work\codeworkvs\py\py\dachuang\KGQA\KGQA_HLM-master\KGQA\ltp.py", line 33, in get_target_array seg_array=cut_words(words) File "d:\Microsoft VS Code\vs work\codeworkvs\py\py\dachuang\KGQA\KGQA_HLM-master\KGQA\ltp.py", line 8, in cut_words segmentor = pyltp.Segmentor() TypeError: **init**(): incompatible constructor arguments. The following argument types are supported: 1. pyltp.Segmentor(model_path: str, lexicon_path: str = None, force_lexicon_path: str = None)
> 
> Invoked with:
> 
> ![image](https://private-user-images.githubusercontent.com/116648963/323202815-b133fb20-24af-43c1-824e-7c7d0a0966fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNzYzNTcsIm5iZiI6MTcxNTE3NjA1NywicGF0aCI6Ii8xMTY2NDg5NjMvMzIzMjAyODE1LWIxMzNmYjIwLTI0YWYtNDNjMS04MjRlLTdjN2QwYTA5NjZmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOFQxMzQ3MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYmQzNWY3OGFhZDI1ZmNmMzY5MTc4YWFhZDRjMGEyZWY3OGI5OTI5ODVhNzcyNWNlODg2OWQyMjYyOGIyM2ExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jXrbdVJ-O3FAiCTIRgcgfihKbsajWrzQ0Oy-QbuW9Zc) ![image](https://private-user-images.githubusercontent.com/116648963/323202913-b4467c84-76ad-4164-b6d8-84900ab56cc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNzYzNTcsIm5iZiI6MTcxNTE3NjA1NywicGF0aCI6Ii8xMTY2NDg5NjMvMzIzMjAyOTEzLWI0NDY3Yzg0LTc2YWQtNDE2NC1iNmQ4LTg0OTAwYWI1NmNjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOFQxMzQ3MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMmI2NWM0MDBjMzkzYTE5MzY2ODI0MjA1NGJjMjRkNzM5MjgzMjIyMjM2MGRkNDhhOTM4ZjQyYzNiZTYyMTcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.d49mn3vq4ppyOPMNEKSQYaBLCT72pGeT2cblScT9cnM)

segmentor = pyltp.Segmentor(model_path=os.path.join(LTP_DATA_DIR, 'cws.model'))
用这行代码初始化实例，postagger也一样
